### ISSUE TITLE
power calculation for wheels

### ISSUE THREAD

**Issue by mertmzk** [ecostech/roboteq_diff_driver#1]
Hi Ecostech,

To calculate wheel power in open loop you used these formula

`right_power = right_speed / wheel_circumference * 60.0 / 82.0 * 1000.0;` 

Can I ask where do you get these numbers from?

**Comment by aarontan94** [comment]
I am also wondering, have you figured it out @mertmzk  ?

**Comment by attermann** [comment]
Acknowledged that could use some documentation!  I had to actually work through the units myself to figure out what my original intention was.  What that formula does is converts translational speed to RPMs, and then scales power linearly between zero (at stop) and 1000 (at max RPMs).  Max RPMs was hard-coded as 82 at the time this was developed, but this will be replaced by a dynamic setting that will be read from the launch file.
