### ISSUE TITLE
How to determine wheel circumference

### ISSUE THREAD

**Issue by Magmanat** [ecostech/roboteq_diff_driver#15]
For some reason when i run this driver with my sdc2160 roboteq motor controller, and my wheel is about 0.9meter in circumference it moved really slowly when i set the speed to 1 meter per second in x direction, so i had to manually change the circumference and measure the speed of the robot until i got the correct speed ratio at around 0.11 meter in circumference 

Any idea why this issue is happening?

**Comment by attermann** [comment]
I suggest you check your motor encoder specs. The default config is for a quadrature encoder with 900 pulses/revolution and 3600 counts/revolution.
