### ISSUE TITLE
What mode should the motor and encoder be in?

### ISSUE THREAD

**Issue by aarontan94** [ecostech/roboteq_diff_driver#2]
Hello,

I am wondering, what mode should the motor and encoder be in to utilize this driver?

Thank you,
Aaron

**Comment by aarontan94** [comment]
@attermann Thank you for your response.

I have plugged in my sdc2130 with my dc brushed motors (equipped with AMT 102-V encoders) in to my PC. In Roborun, I have configured the controller to closed loop speed mode with the encoders settings set to feedback (I have adjusted the ppr to match my encoder which is 2018). I specified that the max velocity is 217 RPM in the speed setting. When I control my motor using roborun, I can reach the top speed.

When I launch this driver and then control the motor with: rosrun rqt_robot_steering rqt_robot_steering

My motor does not achieve anywhere near its top speed of 217 RPM.

I am wondering, why is that? Is there a setting somewhere that is limiting my motor output?

**Comment by attermann** [comment]
Hi @aarontan94.  Sorry for the late reply.

In case you haven't already solved this, looking at driver.cpp it appears that yes there is indeed a hard-coded limit of 100 on RPM (lines 325-326).  These are settings that were specific to my particular setup when I developed this and did not make it into dynamic settings.  I will have to change that, unless you'd like to do it and submit a pull.  Alternatively, you could just change this (and other hard-coded settings) in your fork temporarily.  Looks like I also have hard-coded values for motor current and max acceleration and deceleration.

In general for testing, my suggestion would be to start with more basic tests to validate your setup.  I haven't use rqt_robot_steering personally so I can't comment on how this might be done, but if you haven't already done so then validate your ppr and cpr settings by running at a low RPM and confirm that indeed the wheels match that RPM.  Do this in both forward and reverse.  Also measure actual translation speed and rotation speed of your robot under given cmdvel conditions to validate your wheel diameter and track width settings.  Enable debug logs and look for logs like "cmdvel rpm right: xx left: xx" to see what motor speeds these commands translate into.

Hope this helps.

Chad.
